### ISSUE TITLE
Problem generating the IK Solver

### ISSUE THREAD

**Issue by yy16808** [rdiankov/openrave#1209]
Hi Im trying to generate an IK solver for my Robot but unfortunately whenI try to generate the IK solver on Ubuntu 16.04 using ROS kinetic

I have a robot info links like that:

name      index parents
base_link 0            
link_1    1            
link_2    2            
link_3    3            
link_4    4            
link_5    5            
link_6    6            
name      index parents

But when I enter the command:

`python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=commercial_robot_v2.dae --iktype=transform6d --baselink=0 --eelink=6 --savefile=$(pwd)/ikfast61.cpp`

 I get the following error:

`INFO: [[-10000000001**(1/2)/10000000001, 0, 100000*10000000001**(1/2)/10000000001, 6250000/36316087],[0, 1, 0, 472047/20000000],[-100000*10000000001**(1/2)/10000000001, 0, -10000000001**(1/2)/10000000001, 12500000/14532529]]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 9587, in <module>
    chaintree = solver.generateIkSolver(options.baselink,options.eelink,options.freeindices,solvefn=solvefn)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_/ikfast.py", line 2282, in generateIkSolver
    while not self.has(LinksRaw[0],*solvejointvars):
IndexError: list index out of range`

I also see the similar problems like that  [https://sourceforge.net/p/openrave/mailman/message/33589224/]()
But I  still could not find the solution

**Comment by yy16808** [comment]
I solve this problem by modifying the urdf file through adding the joint limit,
