### ISSUE TITLE
Infinite recursion crash in ikfast for Translation XYOrientation3D

### ISSUE THREAD

**Issue by benaxelrod** [rdiankov/openrave#300]
I encountered an infinite recursion crash when trying to generate Translation XYOrientation3D ik.  my robot is planar in the XY plane.  its joints are: hinge-hinge-hinge-slider-hinge.  i am using the "master" branch revision number 4610 downloaded on May 9th, 2014.  on Ubuntu 12.04.

i called ikfast like so:
```
openrave.py --database inversekinematics --robot=doorplantest1.xml --iktype=TranslationXYOrientation3D --manipname=packbot_manipulator
```

here is the full traceback.  (with many repeated lines removed for brevity).  

```
baxelrod@it3264u:~/aladdin2/software/prototype-1/openrave$ openrave.py --database inversekinematics --robot=doorplantest1.xml --iktype=TranslationXYOrientation3D --manipname=packbot_manipulator
[openravepy_robot.cpp:854 SetActiveManipulator] SetActiveManipulator(int) is deprecated
openravepy.databases.inversekinematics: generate, Generating inverse kinematics for manip packbot_manipulator: TranslationXYOrientation3D [0, 1, 2], precision=8 (this might take up to 10 min)
openravepy.databases.inversekinematics: generate, creating ik file /home/baxelrod/.openrave/kinematics.53ee6d036f25f69ac73adea48b5b7c85/ikfast71.TranslationXYOrientation3D.0_1_2_f3_4.cpp
/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py:1412: RuntimeWarning: invalid value encountered in divide
  axisangle /= angle
openravepy.ikfast: forwardKinematicsChain, moved translation [0, 0, -1/50] to right end
openravepy.ikfast: forwardKinematicsChain, moved translation [0, 0, 0] to left end
openravepy.ikfast: forwardKinematicsChain, moved translation on intersecting axis [0, 0, 0] to left
openravepy.ikfast: generateIkSolver, [[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[cos(j0), -sin(j0), 0, 0],[sin(j0), cos(j0), 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[1, 0, 0, -7/100],[0, 1, 0, -3/4],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[cos(j1), -sin(j1), 0, 0],[sin(j1), cos(j1), 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[1, 0, 0, -1/10],[0, 1, 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[cos(j2), -sin(j2), 0, 0],[sin(j2), cos(j2), 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[0, 0, 1, -1/5],[0, 1, 0, 0],[-1, 0, 0, 0]]
openravepy.ikfast: generateIkSolver, [[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, j3]]
openravepy.ikfast: generateIkSolver, [[0, 0, -1, 0],[0, 1, 0, 0],[1, 0, 0, -1/5]]
openravepy.ikfast: generateIkSolver, [[cos(j4), -sin(j4), 0, 0],[sin(j4), cos(j4), 0, 0],[0, 0, 1, 0]]
openravepy.ikfast: generateIkSolver, [[1, 0, 0, 0],[0, 1, 0, 0],[0, 0, 1, -1/50]]
openravepy.ikfast: solveFullIK_TranslationAxisAngle4D, ikfast translation axis 3d, globaldir=[1]
[0]
[0], basedir=[1]
[0]
[0]: [j0, j1, j2]
openravepy.ikfast: SolveAllEquations, c=1, [j3, j4] [j0, j1]
openravepy.ikfast: SolvePairVariables, equation relies on unsolved variables([sj0, cj1, sj1]): -14*cj0*cj4*sin(r00)*sin(atan2(sj4, cj4))/5 - 30*cj0*cj4*sin(r00)*cos(atan2(sj4, cj4)) + 30*cj0*cj4*sin(atan2(sj4, cj4))*cos(r00) - 14*cj0*cj4*cos(r00)*cos(atan2(sj4, cj4))/5 + 14*cj0*j3*sin(r00)*sin(atan2(sj4, cj4)) + 150*cj0*j3*sin(r00)*cos(atan2(sj4, cj4)) - 150*cj0*j3*sin(atan2(sj4, cj4))*cos(r00) + 14*cj0*j3*cos(r00)*cos(atan2(sj4, cj4)) - 14*cj0*px - 150*cj0*py - 30*cj0*sj4*sin(r00)*sin(atan2(sj4, cj4)) + 14*cj0*sj4*sin(r00)*cos(atan2(sj4, cj4))/5 - 14*cj0*sj4*sin(atan2(sj4, cj4))*cos(r00)/5 - 30*cj0*sj4*cos(r00)*cos(atan2(sj4, cj4)) - 28*cj0*sin(r00)*sin(atan2(sj4, cj4))/5 - 60*cj0*sin(r00)*cos(atan2(sj4, cj4)) + 60*cj0*sin(atan2(sj4, cj4))*cos(r00) - 28*cj0*cos(r00)*cos(atan2(sj4, cj4))/5 - 4*cj4**2*sin(r00)**2*sin(atan2(sj4, cj4))**2 - 4*cj4**2*sin(r00)**2*cos(atan2(sj4, cj4))**2 - 4*cj4**2*sin(atan2(sj4, cj4))**2*cos(r00)**2 - 4*cj4**2*cos(r00)**2*cos(atan2(sj4, cj4))**2 + 40*cj4*j3*sin(r00)**2*sin(atan2(sj4, cj4))**2 + 40*cj4*j3*sin(r00)**2*cos(atan2(sj4, cj4))**2 + 40*cj4*j3*sin(atan2(sj4, cj4))**2*cos(r00)**2 + 40*cj4*j3*cos(r00)**2*cos(atan2(sj4, cj4))**2 - 40*cj4*px*sin(r00)*sin(atan2(sj4, cj4)) - 40*cj4*px*cos(r00)*cos(atan2(sj4, cj4)) - 40*cj4*py*sin(r00)*cos(atan2(sj4, cj4)) + 40*cj4*py*sin(atan2(sj4, cj4))*cos(r00) + 30*cj4*sj0*sin(r00)*sin(atan2(sj4, cj4)) - 14*cj4*sj0*sin(r00)*cos(atan2(sj4, cj4))/5 + 14*cj4*sj0*sin(atan2(sj4, cj4))*cos(r00)/5 + 30*cj4*sj0*cos(r00)*cos(atan2(sj4, cj4)) - 16*cj4*sin(r00)**2*sin(atan2(sj4, cj4))**2 - 16*cj4*sin(r00)**2*cos(atan2(sj4, cj4))**2 - 16*cj4*sin(atan2(sj4, cj4))**2*cos(r00)**2 - 16*cj4*cos(r00)**2*cos(atan2(sj4, cj4))**2 - 100*j3**2*sin(r00)**2*sin(atan2(sj4, cj4))**2 - 100*j3**2*sin(r00)**2*cos(atan2(sj4, cj4))**2 - 100*j3**2*sin(atan2(sj4, cj4))**2*cos(r00)**2 - 100*j3**2*cos(r00)**2*cos(atan2(sj4, cj4))**2 + 200*j3*px*sin(r00)*sin(atan2(sj4, cj4)) + 200*j3*px*cos(r00)*cos(atan2(sj4, cj4)) + 200*j3*py*sin(r00)*cos(atan2(sj4, cj4)) - 200*j3*py*sin(atan2(sj4, cj4))*cos(r00) - 150*j3*sj0*sin(r00)*sin(atan2(sj4, cj4)) + 14*j3*sj0*sin(r00)*cos(atan2(sj4, cj4)) - 14*j3*sj0*sin(atan2(sj4, cj4))*cos(r00) - 150*j3*sj0*cos(r00)*cos(atan2(sj4, cj4)) + 80*j3*sin(r00)**2*sin(atan2(sj4, cj4))**2 + 80*j3*sin(r00)**2*cos(atan2(sj4, cj4))**2 + 80*j3*sin(atan2(sj4, cj4))**2*cos(r00)**2 + 80*j3*cos(r00)**2*cos(atan2(sj4, cj4))**2 - 100*px**2 + 150*px*sj0 + 40*px*sj4*sin(r00)*cos(atan2(sj4, cj4)) - 40*px*sj4*sin(atan2(sj4, cj4))*cos(r00) - 80*px*sin(r00)*sin(atan2(sj4, cj4)) - 80*px*cos(r00)*cos(atan2(sj4, cj4)) - 100*py**2 - 14*py*sj0 - 40*py*sj4*sin(r00)*sin(atan2(sj4, cj4)) - 40*py*sj4*cos(r00)*cos(atan2(sj4, cj4)) - 80*py*sin(r00)*cos(atan2(sj4, cj4)) + 80*py*sin(atan2(sj4, cj4))*cos(r00) - 14*sj0*sj4*sin(r00)*sin(atan2(sj4, cj4))/5 - 30*sj0*sj4*sin(r00)*cos(atan2(sj4, cj4)) + 30*sj0*sj4*sin(atan2(sj4, cj4))*cos(r00) - 14*sj0*sj4*cos(r00)*cos(atan2(sj4, cj4))/5 + 60*sj0*sin(r00)*sin(atan2(sj4, cj4)) - 28*sj0*sin(r00)*cos(atan2(sj4, cj4))/5 + 28*sj0*sin(atan2(sj4, cj4))*cos(r00)/5 + 60*sj0*cos(r00)*cos(atan2(sj4, cj4)) - 4*sj4**2*sin(r00)**2*sin(atan2(sj4, cj4))**2 - 4*sj4**2*sin(r00)**2*cos(atan2(sj4, cj4))**2 - 4*sj4**2*sin(atan2(sj4, cj4))**2*cos(r00)**2 - 4*sj4**2*cos(r00)**2*cos(atan2(sj4, cj4))**2 - 16*sin(r00)**2*sin(atan2(sj4, cj4))**2 - 16*sin(r00)**2*cos(atan2(sj4, cj4))**2 - 16*sin(atan2(sj4, cj4))**2*cos(r00)**2 - 16*cos(r00)**2*cos(atan2(sj4, cj4))**2 - 2787/50
Traceback (most recent call last):
  File "/usr/local/bin/openrave.py", line 126, in <module>
    database.run(args=args)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1104, in run
    InverseKinematicsModel.RunFromParser(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1069, in RunFromParser
    model = DatabaseGenerator.RunFromParser(Model=Model,parser=parser,robotatts=robotatts,args=args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/__init__.py", line 252, in RunFromParser
    model.autogenerate(options=options)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 644, in autogenerate
    self.generate(iktype=iktype,freejoints=freejoints,precision=precision,forceikbuild=forceikbuild,outputlang=outputlang,ipython=ipython)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 867, in generate
    chaintree = solver.generateIkSolver(baselink=baselink,eelink=eelink,freeindices=self.freeindices,solvefn=solvefn)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 2219, in generateIkSolver
    chaintree = solvefn(self, LinksRaw, jointvars, isolvejointvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 721, in solveFullIK_TranslationXAxisAngleZNorm4D
    return self.ikfast.IKFastSolver.solveFullIK_TranslationAxisAngle4D(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 3223, in solveFullIK_TranslationAxisAngle4D
    tree = self.SolveAllEquations(AllEquations,curvars=solvejointvars[:],othersolvedvars=self.freejointvars,solsubs=self.freevarsubs[:],endbranchtree=endbranchtree)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 6095, in SolveAllEquations
    self.ComputeSolutionComplexity(solution,othersolvedvars,curvars)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 1934, in ComputeSolutionComplexity
    sol.checkforzeros = sol.getPresetCheckForZeros()
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 573, in getPresetCheckForZeros
    zeroeq += abs(coeff.subs(self.dictequations))
  File "/usr/lib/python2.7/dist-packages/sympy/core/expr.py", line 73, in __abs__
    return C.Abs(self)
  File "/usr/lib/python2.7/dist-packages/sympy/core/cache.py", line 101, in wrapper
    func_cache_it_cache[k] = r = func(*args, **kw_args)
  File "/usr/lib/python2.7/dist-packages/sympy/core/function.py", line 174, in __new__
    evaluated = cls.eval(*args)
  File "/usr/lib/python2.7/dist-packages/sympy/functions/elementary/complexes.py", line 250, in eval
    if arg.is_zero:     return arg
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 280, in _what_known_about
    a = getattr(self,'is_'+pk)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 280, in _what_known_about
    a = getattr(self,'is_'+pk)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 280, in _what_known_about
    a = getattr(self,'is_'+pk)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 280, in _what_known_about
    a = getattr(self,'is_'+pk)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 280, in _what_known_about
    a = getattr(self,'is_'+pk)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 369, in getit
    return self._what_known_about(name)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 257, in _what_known_about
    a = getattr(self,'_eval_is_'+k)()
  File "/usr/lib/python2.7/dist-packages/sympy/core/add.py", line 310, in _eval_is_positive
    if r.is_nonnegative and c.is_positive:
…
  File "/usr/lib/python2.7/dist-packages/sympy/core/add.py", line 277, in <lambda>
    _eval_is_bounded = lambda self: self._eval_template_is_attr('is_bounded')
  File "/usr/lib/python2.7/dist-packages/sympy/core/operations.py", line 256, in _eval_template_is_attr
    a = getattr(t, is_attr)
  File "/usr/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 367, in getit
    return self._assumptions[name]
RuntimeError: maximum recursion depth exceeded
```

and here is my robot xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<Robot name="DoorPlanTest" type="GenericRobot">
 <kinbody>
  <Body name="Wall" type="static" >
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>0 0 0</Translation>
      <Geom type="box">
      <extents>0.05 0.5 0.1</extents> <!-- Note: half widths -->
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>0 0.5 0</Translation>
      <diffuseColor>0.0 0.0 1.0</diffuseColor>
    </Geom>
    <Geom type="box">
      <extents>0.05 0.5 0.1</extents> <!-- Note: half widths -->
      <rotationaxis>0 0 1 180</rotationaxis>
      <Translation>0 -1.3 0</Translation>
      <diffuseColor>0.0 0.0 1.0</diffuseColor>
    </Geom>
  </Body>
  <Body name="Door" type="dynamic" >
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>0 0 0</Translation>
        <Geom type="box">
      <extents>0.025 0.4 0.05</extents> <!-- Note: half widths -->
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>0 -0.4 0</Translation>
      <diffuseColor>1.0 0.0 0.0</diffuseColor>
    </Geom>
    <Geom type="box">
      <extents>0.035 0.01 0.05</extents> <!-- Note: half widths -->
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.035 -0.75 0</Translation>
      <diffuseColor>1.0 0.0 0.0</diffuseColor>
    </Geom>
  </Body>
  <joint name="DoorHinge" type="hinge">
    <Body>Wall</Body>
    <Body>Door</Body>
    <axis>0 0 1</axis>
    <limitsdeg>-90 90</limitsdeg>
    <offsetfrom>Wall</offsetfrom>
    <anchor>0 0 0</anchor>
  </joint>
  <Body name="Gripper_distal" type="dynamic" >
    <offsetfrom>Door</offsetfrom>
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>-0.07 -0.75 0</Translation>
        <Geom type="box">
      <extents>0.05 0.02 0.01</extents>
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.05 0 0</Translation>
      <diffuseColor>0 1 0</diffuseColor>
    </Geom>
  </Body>
  <joint name="CageGrasp" type="hinge">
    <Body>Door</Body>
    <Body>Gripper_distal</Body>
    <axis>0 0 1</axis>
    <limitsdeg>-10 10</limitsdeg>
    <offsetfrom>Gripper_distal</offsetfrom>
    <anchor>0 0 0</anchor>
  </joint>
  <Body name="Gripper_proximal_Arm_distal" type="dynamic" >
    <offsetfrom>Gripper_distal</offsetfrom>
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>-0.1 0 0</Translation>
        <Geom type="box">
      <extents>0.1 0.02 0.01</extents>
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.1 0 0</Translation>
      <diffuseColor>1 0 1</diffuseColor>
    </Geom>
  </Body>
  <joint name="Breakaway" type="hinge">
    <Body>Gripper_distal</Body>
    <Body>Gripper_proximal_Arm_distal</Body>
    <axis>0 0 1</axis>
    <limitsdeg>-50 50</limitsdeg>
    <offsetfrom>Gripper_proximal_Arm_distal</offsetfrom>
    <anchor>0 0 0</anchor>
  </joint>
  <Body name="Arm_proximal" type="dynamic" >
    <offsetfrom>Gripper_proximal_Arm_distal</offsetfrom>
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>-0.2 0 0</Translation>
        <Geom type="box">
      <extents>0.1 0.02 0.01</extents>
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.1 0 0</Translation>
      <diffuseColor>1 1 0</diffuseColor>
    </Geom>
  </Body>
  <joint name="PseudoArm" type="slider">
    <Body>Gripper_proximal_Arm_distal</Body>
    <Body>Arm_proximal</Body>
    <axis>1 0 0</axis>
    <limits>-1 1</limits>
    <offsetfrom>Arm_proximal</offsetfrom>
    <anchor>0 0 0</anchor>
  </joint>
  <Body name="Packbot" type="dynamic" >
    <offsetfrom>Arm_proximal</offsetfrom>
    <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
    <Translation>-0.2 0 -0.02</Translation>
        <Geom type="box">
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.2 0 0</Translation> <!-- Note: half widths -->
      <extents>0.294 0.1275 0.01</extents>
      <diffuseColor>0.0 0.0 1.0</diffuseColor>
    </Geom>
        <Geom type="box">
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.2 0.165 0</Translation> <!-- Note: half widths -->
      <extents>0.344 0.0375 0.01</extents>
      <diffuseColor>0.0 1.0 1.0</diffuseColor>
    </Geom>
        <Geom type="box">
      <RotationMat>0 0 0 0 0 0 0 0 0</RotationMat>
      <Translation>-0.2 -0.165 0</Translation> <!-- Note: half widths -->
      <extents>0.344 0.0375 0.01</extents>
      <diffuseColor>0.0 1.0 1.0</diffuseColor>
    </Geom>
      </Body>
  <joint name="Shoulder" type="hinge">
    <Body>Arm_proximal</Body>
    <Body>Packbot</Body>
    <axis>0 0 1</axis>
    <limitsdeg>-180 180</limitsdeg>
    <offsetfrom>Packbot</offsetfrom>
    <anchor>0 0 0</anchor>
  </joint>
  <adjacent>Door Wall</adjacent>
  <adjacent>Gripper_distal Door</adjacent>
  <adjacent>Gripper_proximal_Arm_distal Door</adjacent>
  <adjacent>Gripper_proximal_Arm_distal Gripper_distal</adjacent>
  <adjacent>Arm_proximal Door</adjacent>
  <adjacent>Arm_proximal Gripper_distal</adjacent>
  <adjacent>Arm_proximal Gripper_proximal_Arm_distal</adjacent>
  <adjacent>Packbot Arm_proximal</adjacent>
  <adjacent>Packbot Gripper_proximal_Arm_distal</adjacent>
  <adjacent>Packbot Gripper_distal</adjacent>
 </kinbody>
  <Manipulator name="packbot_manipulator">
    <base>Wall</base>
    <effector>Packbot</effector>
    <direction>1 0 0</direction>
    <translation>-0.2 0 0</translation>
  </Manipulator>
</Robot>
```

**Comment by rdiankov** [comment]
FYI, i'm only testing with sympy v0.7.1 until i find the time to upgrade and retest everything.

a lot of users have reported problems with higher versions that do not happen on sympy v0.7.1...
