### ISSUE TITLE
YouBot  example : thinbox.kinbody.xml

### ISSUE THREAD

**Issue by madratman** [rdiankov/openrave#336]
$ openrave.py --database grasping --robot=robots/kuka-youbot.zae --manipulatordirection="0 1 0" --target=thinbox.kinbody.xml
[libopenrave.cpp:650] could not find file "thinbox.kinbody.xml"
Traceback (most recent call last):
  File "/usr/bin/openrave.py", line 126, in <module>
    database.run(args=args)
  File "/usr/lib/python2.7/dist-packages/openravepy/_openravepy_0_8/databases/grasping.py", line 1092, in run
    GraspingModel.RunFromParser(Model=CreateModel, parser=parser,args=args,defaultviewer=True,*margs,**kwargs)
  File "/usr/lib/python2.7/dist-packages/openravepy/_openravepy_0_8/databases/__init__.py", line 224, in RunFromParser
    options,model = DatabaseGenerator.InitializeFromParser(Model,parser,orgenv,args,robotatts,defaultviewer,allowkinbody)
  File "/usr/lib/python2.7/dist-packages/openravepy/_openravepy_0_8/databases/__init__.py", line 205, in InitializeFromParser
    model = Model(robot=robot)
  File "/usr/lib/python2.7/dist-packages/openravepy/_openravepy_0_8/databases/grasping.py", line 1088, in CreateModel
    target.SetTransform(eye(4))
AttributeError: 'NoneType' object has no attribute 'SetTransform'

**Comment by madratman** [comment]
Example works with 
$ openrave.py --database grasping --robot=robots/kuka-youbot.zae --manipulatordirection="0 1 0" --target=data/thinbox.kinbody.xml
