### ISSUE TITLE
IKFast fails for included Barrett WAM robot

### ISSUE THREAD

**Issue by DavidB-CMU** [rdiankov/openrave#387]
Hi,

IKFast fails to solve for the included Barrett WAM robot.

I run this:  
`$ openrave.py --database inversekinematics --robot="openrave/src/robots/barrettwam.robot.xml" --manipname="left_wam"`

The error is this:  
> TypeError: symbolic boolean expression has no truth value.

(more output is included below)

I'm running: 
 - Latest OpenRAVE master branch compiled from source 
 - Ubuntu Trusty 14.04.3 LTS 
 - numpy 1:1.8.2-0ubuntu0.1 

I mention the numpy version because if I upgrade to numpy 1.10.1 then IKFast fails to run due to a bug in numpy.

--------------

<snip>

> openravepy.ikfast: AddSolution, depth=0, c=136, iter=2/5, starting newcases: set([Abs(j5)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=141, [j0, j1, j3, j2, j5, j6] [j4]: cases=set([Abs(j5)])
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [new_r01*cos(j4) + new_r11*sin(j4) + sj6, cj6*sin(j4) + new_r01 + sj6*cos(j4), -cj6*cos(j4) + new_r00 + sj6*sin(j4), -cj6*cos(j4) + new_r11 + sj6*sin(j4), -cj6 + new_r00*cos(j4) + new_r10*sin(j4), -cj6*sin(j4) + new_r10 - sj6*cos(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6**2 - new_r01**2 + 1, -cj6*sj6 + new_r01*new_r11) = Abs(-cj6*sj6 + new_r01*new_r11) + Abs(-cj6**2 - new_r01**2 + 1) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [new_r01*cos(j4) + new_r11*sin(j4) + sj6, cj6*sin(j4) + new_r01 + sj6*cos(j4), -cj6*cos(j4) + new_r00 + sj6*sin(j4), -cj6*cos(j4) + new_r11 + sj6*sin(j4), -cj6 + new_r00*cos(j4) + new_r10*sin(j4), -cj6*sin(j4) + new_r10 - sj6*cos(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r01, cj6**2 + new_r00*new_r11 - 1) = Abs(-cj6*sj6 - new_r00*new_r01) + Abs(cj6**2 + new_r00*new_r11 - 1) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [new_r01*cos(j4) + new_r11*sin(j4) + sj6, cj6*sin(j4) + new_r01 + sj6*cos(j4), -cj6*cos(j4) + new_r00 + sj6*sin(j4), -cj6*cos(j4) + new_r11 + sj6*sin(j4), -cj6 + new_r00*cos(j4) + new_r10*sin(j4), -cj6*sin(j4) + new_r10 - sj6*cos(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r01*new_r11, cj6**2 + new_r11**2 - 1) = Abs(-cj6*sj6 - new_r01*new_r11) + Abs(cj6**2 + new_r11**2 - 1) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [new_r01*cos(j4) + new_r11*sin(j4) + sj6, cj6*sin(j4) + new_r01 + sj6*cos(j4), -cj6*cos(j4) + new_r00 + sj6*sin(j4), -cj6*cos(j4) + new_r11 + sj6*sin(j4), -cj6 + new_r00*cos(j4) + new_r10*sin(j4), -cj6*sin(j4) + new_r10 - sj6*cos(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6**2 - new_r01**2 + 1, -cj6*sj6 + new_r01*new_r11) = Abs(-cj6*sj6 + new_r01*new_r11) + Abs(-cj6**2 - new_r01**2 + 1) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r01, cj6**2 + new_r00*new_r11 - 1) = Abs(-cj6*sj6 - new_r00*new_r01) + Abs(cj6**2 + new_r00*new_r11 - 1) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r01*new_r11, cj6**2 + new_r11**2 - 1) = Abs(-cj6*sj6 - new_r01*new_r11) + Abs(cj6**2 + new_r11**2 - 1) all zeros check
> openravepy.ikfast: AddSolution, depth=0, c=136, iter=2/5, adding newcases: set([Abs(j5)])
> openravepy.ikfast: AddSolution, depth=0, c=136, iter=3/5, starting newcases: set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=143, [j0, j1, j3, j2, j5, j6] [j4]: cases=set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [cj6 + new_r00*cos(j4) + new_r10*sin(j4), cj6*cos(j4) + new_r00 + sj6*sin(j4), cj6*sin(j4) + new_r01 - sj6*cos(j4), cj6*sin(j4) + new_r10 - sj6*cos(j4), new_r01*cos(j4) + new_r11*sin(j4) - sj6, -cj6*cos(j4) + new_r11 - sj6*sin(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6**2 + new_r00**2, cj6*sj6 - new_r00*new_r10) = Abs(-cj6**2 + new_r00**2) + Abs(cj6*sj6 - new_r00*new_r10) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [cj6 + new_r00*cos(j4) + new_r10*sin(j4), cj6*cos(j4) + new_r00 + sj6*sin(j4), cj6*sin(j4) + new_r01 - sj6*cos(j4), cj6*sin(j4) + new_r10 - sj6*cos(j4), new_r01*cos(j4) + new_r11*sin(j4) - sj6, -cj6*cos(j4) + new_r11 - sj6*sin(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r01, -cj6**2 + new_r01*new_r10) = Abs(-cj6**2 + new_r01*new_r10) + Abs(-cj6*sj6 - new_r00*new_r01) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [cj6 + new_r00*cos(j4) + new_r10*sin(j4), cj6*cos(j4) + new_r00 + sj6*sin(j4), cj6*sin(j4) + new_r01 - sj6*cos(j4), cj6*sin(j4) + new_r10 - sj6*cos(j4), new_r01*cos(j4) + new_r11*sin(j4) - sj6, -cj6*cos(j4) + new_r11 - sj6*sin(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r10, -cj6**2 + new_r10**2) = Abs(-cj6**2 + new_r10**2) + Abs(-cj6*sj6 - new_r00*new_r10) all zeros check
> openravepy.ikfast: solveSingleVariable, j4 solution: equations used for atan2: [cj6 + new_r00*cos(j4) + new_r10*sin(j4), cj6*cos(j4) + new_r00 + sj6*sin(j4), cj6*sin(j4) + new_r01 - sj6*cos(j4), cj6*sin(j4) + new_r10 - sj6*cos(j4), new_r01*cos(j4) + new_r11*sin(j4) - sj6, -cj6*cos(j4) + new_r11 - sj6*sin(j4), -new_r00*sin(j4) + new_r10*cos(j4) - sj6, -cj6 - new_r01*sin(j4) + new_r11*cos(j4)]
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6**2 + new_r00**2, cj6*sj6 - new_r00*new_r10) = Abs(-cj6**2 + new_r00**2) + Abs(cj6*sj6 - new_r00*new_r10) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r01, -cj6**2 + new_r01*new_r10) = Abs(-cj6**2 + new_r01*new_r10) + Abs(-cj6*sj6 - new_r00*new_r01) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(-cj6*sj6 - new_r00*new_r10, -cj6**2 + new_r10**2) = Abs(-cj6**2 + new_r10**2) + Abs(-cj6*sj6 - new_r00*new_r10) all zeros check
> openravepy.ikfast: AddSolution, depth=0, c=136, iter=3/5, adding newcases: set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: AddSolution, depth=0, c=136, iter=4/5, starting newcases: set([Abs(new_r02) + Abs(new_r12)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=145, [j0, j1, j3, j2, j5, j6] [j4]: cases=set([Abs(new_r02) + Abs(new_r12)])
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r01, new_r11) = Abs(new_r01) + Abs(new_r11) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r01, new_r11) = Abs(new_r01) + Abs(new_r11) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r00, new_r10) = Abs(new_r00) + Abs(new_r10) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r00, new_r10) = Abs(new_r00) + Abs(new_r10) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r10, -new_r00) = Abs(new_r00) + Abs(new_r10) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r10, -new_r00) = Abs(new_r00) + Abs(new_r10) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r11, -new_r01) = Abs(new_r01) + Abs(new_r11) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r11, -new_r01) = Abs(new_r01) + Abs(new_r11) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r01*new_r22, new_r11*new_r22) = Abs(new_r01*new_r22) + Abs(new_r11*new_r22) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r01*new_r22, new_r11*new_r22) = Abs(new_r01*new_r22) + Abs(new_r11*new_r22) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r00*new_r22, new_r10*new_r22) = Abs(new_r00*new_r22) + Abs(new_r10*new_r22) all zeros check
> openravepy.ikfast: checkForDivideByZero, adding atan2(new_r00*new_r22, new_r10*new_r22) = Abs(new_r00*new_r22) + Abs(new_r10*new_r22) all zeros check
> openravepy.ikfast: AddSolution, depth=0, c=136, iter=4/5, adding newcases: set([Abs(new_r02) + Abs(new_r12)])
> openravepy.ikfast: AddSolution, dual constraint [(new_r02, 0), (new_r12, 0), (new_r20, 0), (new_r21, 0), (new_r10**2, -new_r00**2 + 1), (new_r10**3, -new_r00**2*new_r10 + new_r10), (new_r01**2, -new_r00**2 + 1)] in Abs(new_r02) + Abs(new_r12)
> openravepy.ikfast: AddSolution, depth=0, c=94, iter=0/3, starting newcases: set([Abs(j5)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=147, [j0, j1, j3, j2, j5] [j4, j6]: cases=set([Abs(j5)])
> openravepy.ikfast: IsHinge, IsHinge returning false for variable dummy
> openravepy.ikfast: solveSingleVariable, dummy solution: equations used for atan2: [new_r01 + sin(dummy), new_r00 - cos(dummy), new_r11 - cos(dummy), new_r10 - sin(dummy)]
> openravepy.ikfast: IsHinge, IsHinge returning false for variable dummy
> openravepy.ikfast: solveSingleVariable, dummy solution: equations used for atan2: [new_r01 + sin(dummy), new_r00 - cos(dummy), new_r11 - cos(dummy), new_r10 - sin(dummy)]
> openravepy.ikfast: SolveAllEquations, found two aligning axes j4 + j6: [new_r01 + sin(dummy), new_r00 - cos(dummy), new_r11 - cos(dummy), new_r10 - sin(dummy)]
> openravepy.ikfast: AddSolution, depth=0, c=94, iter=0/3, adding newcases: set([Abs(j5)])
> openravepy.ikfast: AddSolution, depth=0, c=94, iter=1/3, starting newcases: set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=149, [j0, j1, j3, j2, j5] [j4, j6]: cases=set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: IsHinge, IsHinge returning false for variable dummy
> openravepy.ikfast: solveSingleVariable, dummy solution: equations used for atan2: [new_r01 + sin(dummy), new_r00 + cos(dummy), new_r11 - cos(dummy), new_r10 + sin(dummy)]
> openravepy.ikfast: IsHinge, IsHinge returning false for variable dummy
> openravepy.ikfast: solveSingleVariable, dummy solution: equations used for atan2: [new_r01 + sin(dummy), new_r00 + cos(dummy), new_r11 - cos(dummy), new_r10 + sin(dummy)]
> openravepy.ikfast: SolveAllEquations, found two aligning axes j4 - j6: [new_r01 + sin(dummy), new_r00 + cos(dummy), new_r11 - cos(dummy), new_r10 + sin(dummy)]
> openravepy.ikfast: AddSolution, depth=0, c=94, iter=1/3, adding newcases: set([Abs(j5 - 3.14159265358979323846264338328)])
> openravepy.ikfast: AddSolution, depth=0, c=94, iter=2/3, starting newcases: set([Abs(new_r02) + Abs(new_r12)])
> openravepy.ikfast: SolveAllEquations, depth=1 c=151, [j0, j1, j3, j2, j5] [j4, j6]: cases=set([Abs(new_r02) + Abs(new_r12)])
> openravepy.ikfast: SolvePairVariables, equation relies on unsolved variables([sj4, cj6, sj6]): -cj4**2*new_r01**2*new_r22**4 - cj4**2*new_r01**2 + cj4**2*new_r11**2*new_r22**4 + cj4**2*new_r11**2 - 2*cj4*new_r01*new_r11*new_r22**4*sj4 - 2*cj4*new_r01*new_r11*sj4 - 2*cj6**2*new_r22**2 - new_r11**2*new_r22**4 - new_r11**2 + 2*new_r22**2
> Traceback (most recent call last):
>   File "/usr/local/bin/openrave.py", line 126, in <module>
>     database.run(args=args)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1113, in run
>     InverseKinematicsModel.RunFromParser(*args,**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1078, in RunFromParser
>     model = DatabaseGenerator.RunFromParser(Model=Model,parser=parser,robotatts=robotatts,args=args,**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/__init__.py", line 262, in RunFromParser
>     model.autogenerate(options=options)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 648, in autogenerate
>     self.generate(iktype=iktype,freejoints=freejoints,precision=precision,forceikbuild=forceikbuild,outputlang=outputlang,ipython=ipython,ikfastmaxcasedepth=ikfastmaxcasedepth)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 874, in generate
>     chaintree = solver.generateIkSolver(baselink=baselink,eelink=eelink,freeindices=self.freeindices,solvefn=solvefn)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 2264, in generateIkSolver
>     chaintree = solvefn(self, LinksRaw, jointvars, isolvejointvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 741, in solveFullIK_6D
>     return self.ikfast.IKFastSolver.solveFullIK_6D(*args,**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 2858, in solveFullIK_6D
>     tree = self.TestIntersectingAxes(solvejointvars,Links, LinksInv,endbranchtree)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 2946, in TestIntersectingAxes
>     return self.solve6DIntersectingAxes(T0links,T1links,transvars,rotvars,solveRotationFirst=solveRotationFirst, endbranchtree=endbranchtree)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 3141, in solve6DIntersectingAxes
>     rottree += self.SolveAllEquations(AllEquations,curvars=currotvars,othersolvedvars=othersolvedvars,solsubs=self.freevarsubs[:],endbranchtree=storesolutiontree)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 6667, in SolveAllEquations
>     return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 6766, in AddSolution
>     return [solution[0].subs(solsubs)]+self.SolveAllEquations(AllEquations,curvars=newvars,othersolvedvars=othersolvedvars+[var],solsubs=solsubs+self.Variable(var).subs,endbranchtree=endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 6527, in SolveAllEquations
>     return self.AddSolution(solutions,AllEquations,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=currentcases, currentcasesubs=currentcasesubs, unknownvars=unknownvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 7330, in AddSolution
>     newtree = self.SolveAllEquations(NewEquationsClean,curvars,othersolvedvars,solsubs,endbranchtree,currentcases=newcases, currentcasesubs=newcasesubs, unknownvars=unknownvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 6647, in SolveAllEquations
>     rawsolutions=self.SolvePairVariables(raweqns,var0,var1,othersolvedvars,unknownvars=curvars+unknownvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 8774, in SolvePairVariables
>     return self.SolvePairVariablesHalfAngle(raweqns,var0,var1,othersolvedvars)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 7559, in SolvePairVariablesHalfAngle
>     possiblefinaleq = self.checkFinalEquation(Poly(Malldet,leftvar),subs)
>   File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/ikfast.py", line 7961, in checkFinalEquation
>     if len(coeffs) == 1 and Abs(coeffs[0]) < 2*(10.0**-self.precision):
>   File "/usr/lib/python2.7/dist-packages/sympy/core/relational.py", line 226, in __nonzero__
>     raise TypeError("symbolic boolean expression has no truth value.")
> TypeError: symbolic boolean expression has no truth value.

**Comment by DavidB-CMU** [comment]
The same error message was reported in: 
https://github.com/rdiankov/openrave/issues/376 - ikfast regression: "symbolic boolean expression has no truth value."

**Comment by DavidB-CMU** [comment]
Solved: 
I had to downgrade my version of sympy as suggested in https://github.com/rdiankov/openrave/issues/369

Previously I was using sympy version 0.7.4.1-1 
I removed that using pip and installed 0.7.1 
```
$ sudo pip uninstall sympy
$ sudo pip install sympy==0.7.1
```
