### ISSUE TITLE
tests fail due to missing type converter for boost::shared_ptr<openravepy::PyInterfaceBase>

### ISSUE THREAD

**Issue by morxa** [rdiankov/openrave#427]
If I run `test/run_tests.py`, many tests fail with an error similar to the following:

```
======================================================================
ERROR: test_global.test_global.tutorialexample('../docs/source/tutorials/openravepy_examples/using_link_statistics',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/till/code/openrave/test/test_global.py", line 37, in __call__
    module=imp.load_module(modulename, fp, pathname, description)
  File "/home/till/code/openrave/test/../docs/source/tutorials/openravepy_examples/using_link_statistics.py", line 8, in <module>
    robot = env.GetRobots()[0] # get the first robot
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<openravepy::PyInterfaceBase>
```

I'm using Fedora 24 with
* Boost 1.60
* Python 2.7.12
* GCC 6.1.1
* python2-coverage 4.2
* python2-nose 1.3.7

I tested this on commit 8bfb8a6 and 30baaa6, the issue is the same.

**Comment by morxa** [comment]
This is a boost issue and has been fixed, see boostorg/python#56. A fix in Fedora is currently pending for Fedora 24, see [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1358725)
