### ISSUE TITLE
inversekinematics.py: 371 TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by nxdefiant** [rdiankov/openrave#721]
Hi, when running
`openrave.py --database inversekinematics --robot=robots/barrettwam.robot.xml --usecached --iktests=100 --show`
on branch latest_stable (but seems unchanged in master) on a ubuntu:16.04 docker image I get the following exception:

> Traceback (most recent call last):
  File "/usr/local/bin/openrave.py", line 126, in <module>
    database.run(args=args)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1123, in run
    InverseKinematicsModel.RunFromParser(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 1088, in RunFromParser
    model = DatabaseGenerator.RunFromParser(Model=Model,parser=parser,robotatts=robotatts,args=args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/__init__.py", line 260, in RunFromParser
    model.show(options=options)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 999, in show
    self.setrobot(0.05)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/databases/inversekinematics.py", line 371, in setrobot
    if len(self.freeindices) > 0 and self.freeinc is not None and len(self.freeinc) == len(self.freeindices):
TypeError: object of type 'float' has no len()

As workaround I added a float check in like 371 by changing
`if len(self.freeindices) > 0 and self.freeinc is not None and len(self.freeinc) == len(self.freeindices):`
to
`if len(self.freeindices) > 0 and self.freeinc is not None and type(self.freeinc) != float and len(self.freeinc) == len(self.freeindices):`
which seems to work for now.

**Comment by jgvictores** [comment]
The fix isn't bad, but the issue itself seems related to sympy, similar to https://github.com/rdiankov/openrave/issues/584 and many other python-related issues.

A downgrade to sympy version '0.7.1' should do the trick for now.
